-- Reversa del paso 1: borra triggers, función y columnas numeric. Las Float nunca se tocaron.
BEGIN;
DROP TRIGGER IF EXISTS d1_plata ON "Service";
ALTER TABLE "Service" DROP COLUMN IF EXISTS "priceDec", DROP COLUMN IF EXISTS "residentPriceDec", DROP COLUMN IF EXISTS "depositAmountDec";
DROP TRIGGER IF EXISTS d1_plata ON "Product";
ALTER TABLE "Product" DROP COLUMN IF EXISTS "priceDec", DROP COLUMN IF EXISTS "pricePerKgDec";
DROP TRIGGER IF EXISTS d1_plata ON "Appointment";
ALTER TABLE "Appointment" DROP COLUMN IF EXISTS "priceAtBookingDec", DROP COLUMN IF EXISTS "discountAmountDec";
DROP TRIGGER IF EXISTS d1_plata ON "CommissionPayout";
ALTER TABLE "CommissionPayout" DROP COLUMN IF EXISTS "amountDec";
DROP TRIGGER IF EXISTS d1_plata ON "Payment";
ALTER TABLE "Payment" DROP COLUMN IF EXISTS "amountDec";
DROP TRIGGER IF EXISTS d1_plata ON "Coupon";
ALTER TABLE "Coupon" DROP COLUMN IF EXISTS "valueDec";
DROP TRIGGER IF EXISTS d1_plata ON "Order";
ALTER TABLE "Order" DROP COLUMN IF EXISTS "subtotalDec", DROP COLUMN IF EXISTS "discountDec", DROP COLUMN IF EXISTS "totalDec";
DROP TRIGGER IF EXISTS d1_plata ON "OrderItem";
ALTER TABLE "OrderItem" DROP COLUMN IF EXISTS "unitPriceDec", DROP COLUMN IF EXISTS "lineTotalDec";
DROP TRIGGER IF EXISTS d1_plata ON "CashSession";
ALTER TABLE "CashSession" DROP COLUMN IF EXISTS "openingFloatDec", DROP COLUMN IF EXISTS "closingExpectedDec", DROP COLUMN IF EXISTS "closingCountedDec", DROP COLUMN IF EXISTS "closingDiffDec";
DROP TRIGGER IF EXISTS d1_plata ON "CashMovement";
ALTER TABLE "CashMovement" DROP COLUMN IF EXISTS "amountDec";
DROP TRIGGER IF EXISTS d1_plata ON "StockPurchase";
ALTER TABLE "StockPurchase" DROP COLUMN IF EXISTS "totalCostDec";
DROP TRIGGER IF EXISTS d1_plata ON "StockPurchaseItem";
ALTER TABLE "StockPurchaseItem" DROP COLUMN IF EXISTS "unitCostDec", DROP COLUMN IF EXISTS "lineTotalDec";
DROP TRIGGER IF EXISTS d1_plata ON "StockMovement";
ALTER TABLE "StockMovement" DROP COLUMN IF EXISTS "unitCostDec";
DROP FUNCTION IF EXISTS d1_sincronizar_plata();
COMMIT;
